### ISSUE TITLE
Kicad version and pdf file of sch.

### ISSUE THREAD

**Issue by 931436690** [robin7331/pixel-pump-mainboard#1]
Hi,
  What version of kicad do you use? Can you share the download link of the EDA software?The schematic diagram of the pdf file is easier to view. The files cannot be opened with the 5.1.12 version of kicad.
Thank you very much!

**Comment by robin7331** [comment]
You have to have KiCad nightly in order to open the project.
The min version is ´KiCad Nightly 6.0.0-rc1-46-g1d2fd6d271` as seen in the [readme.md](https://raw.githubusercontent.com/robin7331/pixel-pump-mainboard/main/readme.md)

You can download KiCad nightly here by choosing your OS: https://kicad-downloads.s3.cern.ch/index.html?prefix=

Good point with the schematics as PDF. Will add it!
